### PR TITLE
Update 2021-04-06 Thailand

### PR DESCRIPTION
**Pull request by nutjane**
Update Vaccination info of Thailand as of 2021-04-06. 
Source: Ministry of Public Health

https://ddc.moph.go.th/uploads/ckeditor2//files/Dialy%20report%202021-04-06.pdf

### CODE REVIEW

**Comment by edomt** [comment]
Thank you @nutjane - is this report published on a daily basis? If so, could you please send us the link to the page where they're listed? It looks like we may be able to automate our data collection for Thailand based on this.

**Comment by nutjane** [comment]
Hi @edomt - this report is published daily listed on this page https://ddc.moph.go.th/dcd/pagecontent.php?page=647&dept=dcd. 

Unfortunately, they're in .pdf format and all texts are in Thai.  The good thing is they're templated so if we could scrape and extract for particular text/ pattern, then we could automate. 

Will look into automate options :)

**Comment by edomt** [comment]
Thank you @nutjane 

@lucasrodes Another possible automation :)

**Comment by nutjane** [comment]
@petchumpriwan

**Comment by petchumpriwan** [comment]
I'm working on automation script for Thailand, This may help you because report is in PDF format and it's all in Thai :)

**Pull request closed without merging**
