### PR TITLE
Adding 8th and 9th September Vac

### PR DESCRIPTION
**Pull request by ErmanBelegu**
Adding 8th and 9th September for Vaccination Data in Kosovo.

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @ErmanBelegu,
Thanks for your contribution. We will add these new data points to the dataset!

For vaccination data reports, I'd suggest that you take a look at our [contribution guideline](https://github.com/owid/covid-19-data/blob/master/scripts/docs/vaccinations/CONTRIBUTE.md#Add-new-country-automations). As our process to add data for Kosovo is manual, we welcome data reports in thread #230. Also, note that the date format that we use is YYYY-MM-DD.


Kind regards,
Lucas

**Comment by ErmanBelegu** [comment]
@lucasrodes Thanks a lot for your information.

As I can see, if I want to contribute with numbers, I need to comment on thread #230 ?
Is this correct?

**Comment by lucasrodes** [comment]
That is correct!
Thank you very much :)

**Comment by ErmanBelegu** [comment]
Perfect, very easy for us.

Great job.

**Pull request closed without merging**
