### PR TITLE
Refactoring the pipeline for incremental scripts - II

### PR DESCRIPTION
**Pull request by covid19owid**
@ValentinMouret @lucasrodes  @edomt

Pipeline for couple of incremental scripts have been updated to Series. Can you please provide your reviews, comments and feedback.

### CODE REVIEW

**Review by ValentinMouret — COMMENTED** [review]
I made suggestions as I think some parts are overly complex. Tell me what you think :)

**Comment by covid19owid** [comment]
@ValentinMouret  Thanks a lot again! . Will make the suggested changes.

**Comment by covid19owid** [comment]
@ValentinMouret and @edomt 

Thank you once again. Suggested changes have been made.
Looks like Peru script has been moved to batch directory.

**Review by ValentinMouret — APPROVED** [review]
LGTM

**Comment by edomt** [comment]
Thank you for all this!

**Pull request merged**
