### PR TITLE
Peru testing data

### PR DESCRIPTION
**Pull request by 3dgiordano**
Hi all.

I migrated the code from the R version of Peru to python.

The code was tested, but was not tested with the OWID class format.
Apologies if there are any minor errors.

Currently the data server in Peru is experiencing technical problems, but it has been working for the last few days.
Since you had the zip file I can do local testing by changing test_url and pointing it to the zip file hosted elsewhere.

I tried to notify those responsible for the Peru site but I have not had a response from them yet.
It is possible that when you go to review this code, the site will already be working again.

I hope it helps.

Regards
David

cc @camappel

### CODE REVIEW

**Comment by 3dgiordano** [comment]
Hi @edomt and @camappel 

I attach the csv with the latest data that I was able to process locally.
If the server is not yet available to have the batch running, you can use the csv as a reference to update Peru testing data.

[Peru.csv](https://github.com/owid/covid-19-data/files/7918429/Peru.csv)
.

**Comment by lucasrodes** [comment]
Currently, the source is not working. Will leave some days to see if it comes back live.

Otherwise, we may consider this alternate source: github.com/jmcastagnetto/covid-19-peru-data

**Comment by 3dgiordano** [comment]
Hi @lucasrodes.

I tried to contact those responsible for the open data portal and INS but I have not yet had a response.

If I have any news about it, I'll let you know.

When you decide that the waiting time is enough, let me know.
I do the migration to the alternative source, I have no problem helping you with that.

**Comment by lucasrodes** [comment]
I haven't checked the alternative source so far in detail, but it could be helpful. We use a similar source for vaccinations.

**Comment by 3dgiordano** [comment]
@lucasrodes @camappel 
The site is up and running again.

**Review by lucasrodes — APPROVED** [review]
LGTM.

I have tweaked a bit the downloading and reading of the data file, as I was getting some problems with the SSL certificate.

**Review by camappel — APPROVED** [review]
Works on my end, too. Thanks @3dgiordano!

**Pull request merged**
