### PR TITLE
fixes (#2534)

### PR DESCRIPTION
**Pull request by Rouein**

### CODE REVIEW

**Comment by Rouein** [comment]
I am not sure about the last metric but I'll try to find the definition in Azerbaijan and adjust accordingly

**Comment by Rouein** [comment]
According to [this article](https://nk.gov.az/az/article/1921/), a certificate of immunity is issued after recovering from the virus, which is on par with the vaccination certificate but expires after 6 months. After which, if a single dose of vaccine(from 2 dose protocol vaccines) is administered within 56 days, the certificate will be valid indefinitely.

**Comment by edomt** [comment]
@lucasrodes I'm not sure how to interpret this in the light of our usual rules about vaccination protocols. If needed, we may need to use the WHO data to make sure everything is counted properly.

**Comment by lucasrodes** [comment]
Based on what we have been doing thus far, we do not count COVID + one dose as "fully vaccinated", but "vaccinated".

However, I suspect some of these doses might also be part of the booster protocol at this stage. I reached out to them via mail, hopefully, I can get an answer soon.

I've checked data from the WHO, and it is pretty old and not consistent with our current reporting (I will revisit it). 

Another option could be to disregard these doses in our reporting completely.

**Comment by Rouein** [comment]
I doubt that any of it, is a booster protocol dose since that metric is already given. Based on the official document that I linked, this is a new metric which they regard as on par with fully vaccinated.
The options are:
- go with their definition (fully vaccinated)
- considering it is just a single dose of vaccine add it to people vaccinated
- disregard it completely
I personally lean towards the last option (at least until WHO publishes a new report and we can see how they categorized it.)

**Pull request closed without merging**
