### PR TITLE
Test moldova new script

### PR DESCRIPTION
**Pull request by Rouein**
python script for Moldova's test data(daily change) using the ministry's website as a source (the old source was not providing date of the data it had also changed the format from cumulative total to daily change)

### CODE REVIEW

**Comment by Rouein** [comment]
since the new source works with a web driver scraping for old data will take so much time making it almost impossible.

**Comment by Rouein** [comment]
spoke too soon!

**Review by lucasrodes — APPROVED** [review]
LGTM.

This PR changes from `Cumulative total` to `Daily change in cumulative total`.

The motivation for this is the availability of the metrics. It looks like daily updates on the latter are available.

**Comment by Rouein** [comment]
Unfortunately, that's the most reliable source I could find(the governmental website), and still on some occasions the do not post the announcement containing the data.  So, for the sake of accuracy I had to stick with daily change in cumulative data.

**Review by camappel — APPROVED** [review]
This works for me. Thanks!

**Pull request merged**
