### PR TITLE
Cambodia - Vaccination update 12-Apr-21

### PR DESCRIPTION
**Pull request by VIthaya97**
Cambodia covid-19 vaccination update 12 April 2021:
- Total doses administered: 1,371,536
- One dose given: 1,099,811
- Two doses given (fully vaccinated): 271,725

Sources:
MoH: http://www.freshnewsasia.com/index.php/en/localnews/193533-2021-04-12-16-23-12.html
MoD: http://www.freshnewsasia.com/index.php/en/localnews/193511-2021-04-12-14-27-50.html

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @VIthaya97,
Thanks for reporting.

Quick question, could you help me find where the numbers for the second dose can be found in your references?

**Comment by VIthaya97** [comment]
Hi @lucasrodes, the details are as follows:
+ Total one dose: 1,099,811
- Administered by MoH: 850,798
- Administered by MoD: 249,013

+ Total two doses: 271,725
- Administered by MoH: 143,902
- Administered by MoD: 127,823

Sources are in the above links (retrieved from the information published by MoH and MoD).

**Comment by VIthaya97** [comment]
Hi @lucasrodes, here are the columns that you can see from the websites:
- MoD:
Screen Shot 2021-04-13 at 10 20 38 AM

- MoH:
Screen Shot 2021-04-13 at 10 20 23 AM

**Comment by lucasrodes** [comment]
Thank you so much for your help and input, @VIthaya97. It is really helpfull!

**Pull request closed without merging**
