### PR TITLE
Update Moldova.csv

### PR DESCRIPTION
**Pull request by nicandr**
fully vaccinated people

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @nicandr,
Thanks for your contribution.

From the website https://vaccinare.gov.md/ we are only able to extract `total_vaccinations`. People vaccinated with two doses no longer suffices for metric `people_fully_vaccinated` as single-dose Johnson&Johnson vaccine is in use.

**Comment by nicandr** [comment]
@lucasrodes 
Hello,

They just didn't update the website so it's makes confusion, what they mean there -  is fully vaccinated people either 2 doses or 1 with Johnson&Johnson

Please check the link below, it's official page of our Ministry of Health, and from there you can check

Toate doze administrate - Total doses

Total vaccinati cu doza 1 - Total vaccinated with 1 dose

Total vaccinati cu doza 2 -  Total vaccinated with 2 dose

Persoane vaccinate cu schema completa - People who have been fully vaccinated, literaly - (People vaccinated with complete scheme)

Total doze adminsitrate ultimele 24 ore - Total doses administred last 24 hours

Total vaccinate cu doza 1 in ultimele 24 ore - Total vaccinated with dose 1 in last 24 hours

Total vaccinate cu doza 2 in ultimele 24 ore -  Total vaccinated with dose 2 in last 24 hours


https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fsanatateprotectiesocialamoldova%2Fposts%2F4224658130921419

**Comment by nicandr** [comment]
Additional website with coid info banners: https://covidinfo.gov.md/stats

**Comment by edomt** [comment]
Thanks, we'll add update our script

**Pull request closed without merging**
