### PR TITLE
2021-03-22

### PR DESCRIPTION
**Pull request by mouhib876**
Tunisia reached 18020 vaccine untill 2021-03-22:
https://www.facebook.com/186480324724413/posts/3967440006628407/

### CODE REVIEW

**Comment by edomt** [comment]
Thanks!

**Comment by mouhib876** [comment]
Hi ,i didn't see any update for 03-22 still on 03-21
Same in the map

Le mar. 23 mars 2021 à 12:25, Edouard Mathieu ***@***.***> a
écrit :

**Comment by edomt** [comment]
@mouhib876  Our data on COVID-19 vaccinations is updated each morning (London time), with the most recent official numbers up to the previous day.

**Comment by mouhib876** [comment]
Oh , I thought that it could be updated any time , good job to evrey one in
this site 👏👏

Le mar. 23 mars 2021 à 15:54, Edouard Mathieu ***@***.***> a
écrit :

**Pull request closed without merging**
