### PR TITLE
Add Algeria ICUs data

### PR DESCRIPTION
**Pull request by yasserkaddour**
Hi everyone, thank you all for this awesome project, 

Reading Hans Rosling "Factfulness" and Steven Pinker "Enlightenment now" radically changed how I see the world, I had a bleak conspiracy driven view of the world, and thankfully now with project like Our World in Data I see how the world is changing for the better and made me a radical optimist. I am truly grateful to Max Roser and all the team behind this awesome project.

About the PR, the Algerian ministry of Health publish little Covid-19 data, vaccination and testing rate are unknown.
However, they do publish daily number of people in ICUs in addition to the usual number of new cases,
recoveries and deaths. The crucial data about ICUs is nowhere readily available, hopefully this will change with this PR.

The data come from scraping the Twitter feed of [the Algerian Ministry of Health](https://twitter.com/Sante_Gouv_dz), you can see [the code of the scrapper](https://github.com/yasserkaddour/covid19-icu-data-algeria) which is heavily "borrowed" from @lucasrodes twitter vaccination scrapper. 

I chose to host the script on my GitHub account for convenience, but I'm willing to host it here if you prefer.

I really hope you take this PR in light of the scarcity of Algerian Covid19 data.

Thanks.

### CODE REVIEW

**Comment by yasserkaddour** [comment]
I set up a GitHub action on my repo to run the script every day and send a pull request that I have to approve manually. I didn't fully automate because I did catch a couple of errors in past tweets. 

There are some days in which the data is missing, I plan on adding them manually from official [WHO publication for Algeria](https://www.afro.who.int/fr/countries/publications?country=980), if that's ok with you.

**Comment by yasserkaddour** [comment]
Is there something holding up this PR? 
Thanks

**Comment by lucasrodes** [comment]
Hi @yasserkaddour,
Thanks for your message and sorry for the late reply.

We will try to find some time next week to review this PR. A very important aspect for us when integrating new sources is whether they will be maintained (and thus ensuring continuous updates).

**Comment by yasserkaddour** [comment]
Super! Looking forward to it!
I can assure you that as long as the ministry publishes the numbers, I will continually update the csv. As I have done for the past few days, the process is semi automated. I just have to review the bot PR once a day.

**Review by psoffie02 — APPROVED** [review]

**Comment by edomt** [comment]
Many thanks @yasserkaddour! 🙂 
This is now part of our data, and [visible in our explorer](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&time=2020-03-01..latest&pickerSort=asc&pickerMetric=location&Metric=ICU+patients&Interval=7-day+rolling+average&Relative+to+Population=false&Align+outbreaks=false&country=~DZA).

**Comment by yasserkaddour** [comment]
Thank you, I am proud to contribute to this project! I am waiting on Algerian vaccination Data to contribute some more.

**Pull request merged**
