### PR TITLE
fixed(test,libya)

### PR DESCRIPTION
**Pull request by Rouein**
I did a touch up on the script and fixed it. also collected the missing data.

### CODE REVIEW

**Comment by Rouein** [comment]
you are welcome.

**Comment by Rouein** [comment]
To make sure I can get as much data as possible I manually added some of the data posts from their facebook posts but still couldn't get a continuous data series.

**Comment by lucasrodes** [comment]
> To make sure I can get as much data as possible I manually added some of the data points from their facebook posts but still couldn't get a continuous data series.

It would be great if you could edit the `Source URL` in the data file for those data points coming from Facebook posts.

**Comment by Rouein** [comment]
OK Done!

**Review by lucasrodes — APPROVED** [review]
Thanks, @Rouein!
LGTM

---
I would suggest not merging with the master so frequently as it "pollutes" the PR thread. It is totally fine to do the merge on our end when reviewing.

**Review by camappel — APPROVED** [review]
Another great contribution - thanks!

**Pull request merged**
