### PR TITLE
Update sri_lanka.py

### PR DESCRIPTION
**Pull request by nipund**

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @nipund,
Thanks for your message.

I tested your script and it is raising the following error:

```
Traceback (most recent call last):
  File "/Users/lucasrodes/repos/covid-19-data/scripts/scripts/vaccinations/src/vax/cmd/get_data.py", line 46, in run
    module.main(*args)
  File "/Users/lucasrodes/repos/covid-19-data/scripts/scripts/vaccinations/src/vax/incremental/sri_lanka.py", line 109, in main
    SriLanka().to_csv(paths)
  File "/Users/lucasrodes/repos/covid-19-data/scripts/scripts/vaccinations/src/vax/incremental/sri_lanka.py", line 95, in to_csv
    data = self.read()
  File "/Users/lucasrodes/repos/covid-19-data/scripts/scripts/vaccinations/src/vax/incremental/sri_lanka.py", line 29, in read
    return self.parse_data(soup)
  File "/Users/lucasrodes/repos/covid-19-data/scripts/scripts/vaccinations/src/vax/incremental/sri_lanka.py", line 41, in parse_data
    vaccine = ", ".join(df_vax.vaccine.map(vaccines_mapping))
TypeError: sequence item 0: expected str instance, float found
2021-06-28 17:46:54 INFO 
```

**Comment by nipund** [comment]
Okay I'll take a look at it

**Comment by nipund** [comment]
I can't run it on the machine I'm on right now, but this change should fix it

**Comment by lucasrodes** [comment]
Thanks @nipund,
It is now working fine!

**Pull request merged**
