### PR TITLE
Solving Conversion to float in case of NAs

### PR DESCRIPTION
**Pull request by Rouein**
Same Can be applied to Vax Util to avoid type conversions such as [Indonesia](https://github.com/owid/covid-19-data/blob/master/scripts/output/vaccinations/main_data/Indonesia.csv)

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @Rouein,
Thanks for your help.

I have generalized the lines you implemented and removed the condition of `NaN` being present in the Series. This way, we ensure that the Series is always "cleaned". For instance, in the case of Chile ([`chile.py`](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/testing/automated_sheets/Chile.csv), the column `Daily change in cumulative total` has no NaN, but still, it would be nice if we could cast the column values to Int.

Furthermore, I have changed the location of the type casting to ensure that it is always applied.

**Comment by Rouein** [comment]
I recommend using this in Vax Incremental as well. and perhaps changing [indonesia.py](https://github.com/owid/covid-19-data/blob/master/scripts/src/cowidev/vax/batch/indonesia.py)

**Comment by lucasrodes** [comment]
Thanks for your suggestion.

This is definitely on our roadmap, once we have the time to add some changes to the vaccination pipeline. I'll let you know once we make progress on this front.

**Review by lucasrodes — APPROVED** [review]
LGTM

**Pull request merged**
