### PR TITLE
Update Sri Lanka.csv

### PR DESCRIPTION
**Pull request by waddey**
Corrected missing numbers from 17th February and added most recent.

### CODE REVIEW

**Comment by edomt** [comment]
Good catch, thank you!

**Comment by waddey** [comment]
Hi, 
I don't see the 21 Feb line added yet. Is there a delay?

**Comment by edomt** [comment]
We add data for Sri Lanka manually through an external system. (There's more information in #230)

**Comment by waddey** [comment]
I did add the data citing sources on commit 533

**Comment by edomt** [comment]
Sorry I meant this part:

> Note that contributions via pull requests are not possible due to the way our data pipeline is set up.

**Comment by waddey** [comment]
Ok, thanks

**Pull request closed without merging**
