### PR TITLE
Chile : Vaccination by age group

### PR DESCRIPTION
**Pull request by covid19owid**
Vaccination by age group has been updated for Chile

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @covid19owid,
Thanks for your help!

I modified the code in order to remove some redundancy in code. Please check this and let me know if you have any question.

Note that object oriented refactoring is not needed, I am just taking the chance to do it.

**Comment by lucasrodes** [comment]
I have noticed an error in source data, we'll wait for it to be resolved to merge this PR.

Track error in source in https://github.com/juancri/covid19-vaccination/issues/29 (Spanish)

**Comment by covid19owid** [comment]
Hi @lucasrodes 

Thanks a lot for reviewing. The code refactoring looks good. We can wait for the source data to be resolved.

**Comment by lucasrodes** [comment]
The issue in source has been fixed,
Could you merge with master @covid19owid? Thanks.

**Pull request merged**
