### PR TITLE
Update Portugal.csv

### PR DESCRIPTION
**Pull request by musicaldoctor**
Updating the vaccine count

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @musicaldoctor, 
for cases like Portugal (which is not automated, see [automation_state.csv](https://github.com/owid/covid-19-data/tree/master/scripts/scripts/vaccinations/automations/automation_state.csv)), new entries are welcome in #230.

**Comment by edomt** [comment]
Thanks @lucasrodes (this has been added with our last update)

**Comment by musicaldoctor** [comment]
@lucasrodes not sure i understood what you meant but portugal doesn't have an official api or data for vaccination provided by the government. what they provide is numbers on press conferences (which are then reported by the media) and their site has an image (!!) for the vaccine count, which will be updated every week.

**Comment by lucasrodes** [comment]
Hi @musicaldoctor,
Sorry if my message was not clear. I'll try to sum up my points below:

- In cases where the process still can't be automated, which seems to be the case in Portugal, new entries are welcome in thread #230. Please refer to this thread for more details.
- Whenever the data import process can be automated, contributions in form of scripts are welcome (refer to #250).
- You can check which countries are currently automated and which not in file [automation_state.csv](https://github.com/owid/covid-19-data/tree/master/scripts/scripts/vaccinations/automations/automation_state.csv)

Thanks for your time and effort 😄 !

**Pull request closed without merging**
