### PR TITLE
Add 1st & 2nd Dose for India vaccination

### PR DESCRIPTION
**Pull request by covid19owid**
**Note** : Data for 1st and 2nd dose would be pulled only when the link becomes available from https://pib.gov.in/AllReleasem.aspx under "Ministry of Health and Family Welfare"

### CODE REVIEW

**Comment by edomt** [comment]
@covid19owid This seems to work only at certain times though: if the collection is done right now for example, the page that lists the reports doesn't include any vaccination data: 

image

**Comment by covid19owid** [comment]
@edomt . The link https://pib.gov.in/AllReleasem.aspx now shows COVID-19 vaccination data. Seems like they would update the page with link towards the end of day.

**Update on COVID-19 Vaccination- Day 36**

**Comment by covid19owid** [comment]
India

**Comment by covid19owid** [comment]
@edomt  please ignore commits 
bc4c605
af3ef95
cb23e3f
a46e2a8
5253c07

**Comment by edomt** [comment]
Hey @covid19owid 
I'm working on a solution that includes a request to the aspx page to directly display the previous day's press reports. I seem to have something working, but I need to test it for a couple more days. I'll report here on Wednesday!

**Comment by covid19owid** [comment]
@edomt  Sure. It's better to have a consistent working script.

**Comment by edomt** [comment]
This _seems_ to work: https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/automations/incremental/india.py

**Pull request closed without merging**
