### PR TITLE
Update Vietnam.csv

### PR DESCRIPTION
**Pull request by Ltn123456**

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @Ltn123456,
Thanks for your help.

One question regarding:

> Tính đến 16 giờ ngày 21-4, tổng cộng đã thực hiện tiêm vaccine phòng Covid-19 đợt 1 và 2 tại 27 tỉnh, thành phố cho 108.897 người người là cán bộ, nhân viên y tế đang trực tiếp điều trị bệnh nhân Covid-19,

Is by any chance possible that the number of total vaccinations included both first and second doses? I am trying to find evidence if Vietnam started second dose administration.

Thanks for your help

**Comment by Ltn123456** [comment]
I think that Vietnam is trying to vaccinate as many people as possible and delay the second dose for to 12 weeks. Every sites I found all state that the dose interval for Oxford–AstraZeneca vaccine in Vietnam is 12 weeks. 

https://ncov.moh.gov.vn/web/guest/-/6847426-1959
https://vnexpress.net/7-nhom-o-tp-hcm-duoc-uu-tien-tiem-vaccine-covid-19-4251197.html
https://tienphong.vn/nhung-dieu-can-biet-khi-tiem-vac-xin-ngua-covid-19-tai-viet-nam-post1319260.tpo
https://dangcongsan.vn/khoa-giao/can-luu-y-nhung-dieu-gi-khi-tiem-vac-xin-covid-19-575918.html
https://tuoitre.vn/8-3-tiem-vac-xin-ngua-covid-19-tai-hai-duong-ha-noi-tp-hcm-20210306093905939.htm

**Comment by Ltn123456** [comment]
The words "đợt" in the sentence above means phase (vaccination rollout phases)

**Comment by lucasrodes** [comment]
Thanks for your help, @Ltn123456

**Pull request closed without merging**
