### PR TITLE
Albania test python script

### PR DESCRIPTION
**Pull request by Rouein**
#2287 is already implemented in this branch!

### CODE REVIEW

**Review by camappel — APPROVED** [review]
This works perfectly, and makes good use of the cowidev module. 

Next, we can work on scraping the missing data points.

Thanks!

**Comment by Rouein** [comment]
the website doesn't have robots.txt and with delay I was being blocked every now and then but finally I managed to get all the missing data.

**Comment by camappel** [comment]
Very impressive work, thank you!

If you feel like making another contribution, perhaps you could adapt the script you used to scrape the missing the data points to do the same for Georgia, as discussed in #2278 ?

**Comment by Rouein** [comment]
can you be more specific? what data is missing for Georgia?

**Comment by Rouein** [comment]
is there no automation script for georgia?

**Pull request merged**
