### PR TITLE
Automate Aruba data pull

### PR DESCRIPTION
**Pull request by covid19owid**
Automate Aruba data pull

### CODE REVIEW

**Comment by edomt** [comment]
Thank you! :)

**Comment by ivanfeli** [comment]
Does this assume that the '1st Vaccine Taken' includes fully vaccinated people too? The people in '2nd Vaccine Taken' are not included in the '1st ...' amount.
The API is a bit misleading.

Amount of shots given is actually '2nd Vaccine' * 2 + '1st Vaccine'

**Comment by lucasrodes** [comment]
Hi @ivanfeli, could you provide a source that verifies that 1st Vaccine field does not include people that have taken the second dose? Thanks

**Comment by ivanfeli** [comment]
Hi @lucasrodes 

Here is the latest update on their Facebook page, https://www.facebook.com/desparuba/photos/a.657791820906808/4277983492220938/

'Total Vacuna Aplica' is 62k, which is equal to the 'Prome dosis' + ('Dos dosis' * 2)

Also, I have been scraping the data every 30 minutes for the past 10 days or so and the numbers on the 1st Vaccine field goes down as the 2nd Vaccine fields goes up.

Here's an excerpt of the data showing this:

```
time,category,requests_pending,first_taken,second_taken,appointments,requests_pending_delta,first_taken_delta,second_taken_delta,appointments_delta
4/22/2021 14:30,total,2745,25987,18783,4756,7,-77,97,-6
4/22/2021 15:00,total,2744,25906,18900,4753,-1,-81,117,-3
```

**Comment by edomt** [comment]
Thank you @ivanfeli, we've now fixed the issue.

**Pull request merged**
