### PR TITLE
enhance(vax, Nepal): New country automation

### PR DESCRIPTION
**Pull request by Rouein**
The administered vaccines reported previously (source:WHO) do not match Nepal's official reports. According to the reports Nepal so far has administered :
- `Johnson&Johnson` (in the reports noted also as J & J)
-  `Moderna`
- `Oxford/AstraZeneca` (in the reports noted also as Covid Shield/ COVISHIELD/Japanese made COVID-19 AstraZeneca/Swedish AstraZeneca)
-  `Pfizer/BioNTech` (in the reports noted as Pfizer)
- `Sinopharm/Beijing` (in the reports noted as VeroCell)

Please note that although `Covaxin`, `Sputnik V` and, `CoronaVac` have all received EUA in Nepal none have been administered.  

This script is base on changes in #2482
This script also resolves one of the tasks in #2430

### CODE REVIEW

**Comment by lucasrodes** [comment]
LGTM. Modified field `vaccine` to correctly reflect vaccines in use.

**Comment by Rouein** [comment]
I wish I could see if you are working on it simultaneously. my bad.

**Comment by lucasrodes** [comment]
Np, @Rouein. 

The export function should have both `attach=True` and `attach_manufacturer=True`, as it exports both main and manufacturer data incrementally. If you can add it, I will merge it afterwards.

**Comment by Rouein** [comment]
ok that should do it.

**Pull request merged**
