### PR TITLE
Iran

### PR DESCRIPTION
**Pull request by Rouein**
Iran Automation Script

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @Rouein,
Thanks for your help.

It seems that the code here is not working. I would suggest using `selenium` instead of `BeautifulSoup` to scrap a JS website. 

In `cowidev` library, we have [ `get_driver`](https://github.com/owid/covid-19-data/blob/917ef3990d76712fdb490556f0b88c33c7520736/scripts/src/cowidev/utils/web/scraping.py#L142-L151) to ease the usage of `selenium`. You may need to install `chromedriver` to correctly run selenium (see [documentation](https://github.com/SeleniumHQ/selenium/tree/trunk/py)).


I added some suggestions to your code to avoid issues related to JS.


The following is working on my end, correctly retrieving the text from the news page

```python
from cowidev.utils.web import get_driver
url = "https://behdasht.gov.ir/%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B4%D9%86%D8%A7%D8%B3%D8%A7%DB%8C%DB%8C-%DB%B1%DB%B4%DB%B2%DB%B1-%D8%A8%DB%8C%D9%85%D8%A7%D8%B1-%D8%AC%D8%AF%DB%8C%D8%AF-%D9%88-%D9%81%D9%88%D8%AA-%DB%B1%DB%B8-%D8%A8%DB%8C%D9%85%D8%A7%D8%B1-%DA%A9%D9%88%D9%88%DB%8C%D8%AF%DB%B1%DB%B9-%D8%AF%D8%B1-%D8%B4%D8%A8%D8%A7%D9%86%D9%87-%D8%B1%D9%88%D8%B2-%DA%AF%D8%B0%D8%B4%D8%AA%D9%87-%D8%AF%D8%B1-%DA%A9%D8%B4%D9%88%D8%B1%E2%81%84-%DB%B2%DB%B8-%D8%A7%D8%B3%D8%AA%D8%A7%D9%86-%D9%85%D8%B1%DA%AF-%D9%88-%D9%85%DB%8C%D8%B1-%D8%B5%D9%81%D8%B1-%D9%88-%DB%8C%DA%A9-%D8%AF%D8%A7%D8%B4%D8%AA%D9%87-%D8%A7%D9%86%D8%AF"
with get_driver() as driver:
    driver.get(url)
    driver.find_element_by_class_name
    tag = driver.find_element_by_xpath("//div[@class='news-content']")
```

**Review by Rouein — COMMENTED** [review]
I use black for formatting . Do you have another preferred method?

**Comment by Rouein** [comment]
> Hi @Rouein, Thanks for your help.
> 
> It seems that the code here is not working. I would suggest using `selenium` instead of `BeautifulSoup` to scrap a JS website.
> 
> In `cowidev` library, we have [ `get_driver`](https://github.com/owid/covid-19-data/blob/917ef3990d76712fdb490556f0b88c33c7520736/scripts/src/cowidev/utils/web/scraping.py#L142-L151) to ease the usage of `selenium`. You may need to install `chromedriver` to correctly run selenium (see [documentation](https://github.com/SeleniumHQ/selenium/tree/trunk/py)).
> 
> I added some suggestions to your code to avoid issues related to JS.
> 
> The following is working on my end, correctly retrieving the text from the news page
> 
> ```python
> from cowidev.utils.web import get_driver
> url = "https://behdasht.gov.ir/%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B4%D9%86%D8%A7%D8%B3%D8%A7%DB%8C%DB%8C-%DB%B1%DB%B4%DB%B2%DB%B1-%D8%A8%DB%8C%D9%85%D8%A7%D8%B1-%D8%AC%D8%AF%DB%8C%D8%AF-%D9%88-%D9%81%D9%88%D8%AA-%DB%B1%DB%B8-%D8%A8%DB%8C%D9%85%D8%A7%D8%B1-%DA%A9%D9%88%D9%88%DB%8C%D8%AF%DB%B1%DB%B9-%D8%AF%D8%B1-%D8%B4%D8%A8%D8%A7%D9%86%D9%87-%D8%B1%D9%88%D8%B2-%DA%AF%D8%B0%D8%B4%D8%AA%D9%87-%D8%AF%D8%B1-%DA%A9%D8%B4%D9%88%D8%B1%E2%81%84-%DB%B2%DB%B8-%D8%A7%D8%B3%D8%AA%D8%A7%D9%86-%D9%85%D8%B1%DA%AF-%D9%88-%D9%85%DB%8C%D8%B1-%D8%B5%D9%81%D8%B1-%D9%88-%DB%8C%DA%A9-%D8%AF%D8%A7%D8%B4%D8%AA%D9%87-%D8%A7%D9%86%D8%AF"
> with get_driver() as driver:
>     driver.get(url)
>     driver.find_element_by_class_name
>     tag = driver.find_element_by_xpath("//div[@class='news-content']")
> ```

I didn't read the util's code so i assumed , you were using selenium in `get _soup` ,I will implement it , thanks!

**Comment by lucasrodes** [comment]
@Rouein Don't worry about the style. We use black, too!

`get_soup` uses [`requests`](https://docs.python-requests.org/en/latest/) and [`BeautifulSoup`](https://www.crummy.com/software/BeautifulSoup/bs4/doc/).

We have some scripts that use the aforementioned `get_driver`: [`uzbekistan.py`](https://github.com/owid/covid-19-data/blob/ad2d0d4f5ee6f5a49a118807fb24360c4ddaea26/scripts/src/cowidev/vax/incremental/uzbekistan.py#L24), [`united_arab_emirates.py`](https://github.com/owid/covid-19-data/blob/ad2d0d4f5ee6f5a49a118807fb24360c4ddaea26/scripts/src/cowidev/vax/incremental/united_arab_emirates.py#L19), [`philipines.py`](https://github.com/owid/covid-19-data/blob/38dabf4ce9b3462cc8b4eb2938d647cb77415b4d/scripts/src/cowidev/vax/incremental/philippines.py#L22).

Thanks for your help.

**Comment by Rouein** [comment]
I see `chromedriver-binary==87.0.4280.88.0` in `requirements.txt`  but it is not imported in `utils.web.scraping` should I import it in the script or is it taken care of on the server side?

**Comment by lucasrodes** [comment]
Hi @Rouein,
That is taken care by `selenium` when it is imported un `cowidev.utils.web.scraping`

Probably you will need to install another version of `chromedriver`, in accordance with the version of your Chrome browser.

**Comment by Rouein** [comment]
I already did upgrade the `chromiedriver` but still received `Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home` which was resolved once I `import chromedriver_binary` so I thought the alternative is to import it in `cowidev.utils.web.scraping` and whoever runs the script only needs to upgrade the `chromedriver-binary` via `pip`

**Comment by Rouein** [comment]
I apologize I just realized `chromedriver-binary` being imported in `scraping` wouldn't change anything so I can just import it in the script to resolve the issue for whoever runs the script.

**Comment by Rouein** [comment]
I am not sure if I should open an issue for this since its trivial but in `set_download_settings` you have `driver.command_executor._commands["send_command"] = ("POST","/session/$sessionId/chromium/send_command",)` even though You have the option for Firefox driver

**Comment by lucasrodes** [comment]
Hi @Rouein,
I am unsure what is the issue.

First thing, make sure you have `chromedriver` install and that selenium works on its own.

The download capabilities from the library only work for chromedriver.

**Comment by Rouein** [comment]
I am not sure either it could be either the OS or python version but it's already resolved with `chromedriver-binary`. but again I assume it's unique to my situation since I'm running linux and using pyenv , it perhaps requires setting the `PATH` manually or importing the library to the script.

**Comment by lucasrodes** [comment]
You should be able to run

```python
from selenium import webdriver

driver = webdriver.Chrome()
```

without any problem.

Perhaps these thread can help: [thread 1](https://stackoverflow.com/questions/48213384/how-to-add-chromedriver-to-path-in-linux), [thread2](https://stackoverflow.com/questions/29858752/error-message-chromedriver-executable-needs-to-be-available-in-the-path)

**Comment by Rouein** [comment]
Again I'm mentioning it as a reference if anybody else later faces the issue. I already have it running just by importing `get_driver` and then `import chromedriver_binary` and its running fine.

**Comment by lucasrodes** [comment]
Appreciate that you share this with the community. 

For the record, what

```python
import chromedriver_binary
```

is ultimately doing is adding `chromedriver` binary to path (as per their docs). You don't need to import it if you already have `chromedriver` binary in path. In my case

```
$ whereis chromedriver
/usr/bin/chromedriver
```

`chromedriver` is under `/usr/bin/`. But might be somewhere else in another one's machine (e.g. `/usr/local/bin/chromedriver`)

**Comment by Rouein** [comment]
> 

or in my case I run google-Chrome browser, so I didn't install the drivers separately

```bash
$whereis chromedriver
chromedriver:                 
```
and 

```bash
$whereis google-chrome
google-chrome: /usr/bin/google-chrome
```
so I just used:
```python
import chromedriver_binary
```

**Comment by Rouein** [comment]
> Hi @Rouein, Thanks for your help.
> 
> It seems that the code here is not working. I would suggest using `selenium` instead of `BeautifulSoup` to scrap a JS website.
> 
> In `cowidev` library, we have [ `get_driver`](https://github.com/owid/covid-19-data/blob/917ef3990d76712fdb490556f0b88c33c7520736/scripts/src/cowidev/utils/web/scraping.py#L142-L151) to ease the usage of `selenium`. You may need to install `chromedriver` to correctly run selenium (see [documentation](https://github.com/SeleniumHQ/selenium/tree/trunk/py)).
> 
> I added some suggestions to your code to avoid issues related to JS.
> 
> The following is working on my end, correctly retrieving the text from the news page
> 
> ```python
> from cowidev.utils.web import get_driver
> url = "https://behdasht.gov.ir/%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1/%D8%B4%D9%86%D8%A7%D8%B3%D8%A7%DB%8C%DB%8C-%DB%B1%DB%B4%DB%B2%DB%B1-%D8%A8%DB%8C%D9%85%D8%A7%D8%B1-%D8%AC%D8%AF%DB%8C%D8%AF-%D9%88-%D9%81%D9%88%D8%AA-%DB%B1%DB%B8-%D8%A8%DB%8C%D9%85%D8%A7%D8%B1-%DA%A9%D9%88%D9%88%DB%8C%D8%AF%DB%B1%DB%B9-%D8%AF%D8%B1-%D8%B4%D8%A8%D8%A7%D9%86%D9%87-%D8%B1%D9%88%D8%B2-%DA%AF%D8%B0%D8%B4%D8%AA%D9%87-%D8%AF%D8%B1-%DA%A9%D8%B4%D9%88%D8%B1%E2%81%84-%DB%B2%DB%B8-%D8%A7%D8%B3%D8%AA%D8%A7%D9%86-%D9%85%D8%B1%DA%AF-%D9%88-%D9%85%DB%8C%D8%B1-%D8%B5%D9%81%D8%B1-%D9%88-%DB%8C%DA%A9-%D8%AF%D8%A7%D8%B4%D8%AA%D9%87-%D8%A7%D9%86%D8%AF"
> with get_driver() as driver:
>     driver.get(url)
>     driver.find_element_by_class_name
>     tag = driver.find_element_by_xpath("//div[@class='news-content']")
> ```

it turned out that it's not just JS its cookies as well so to work you have to `quit()` the driver and create a new one.
Anyways, I tested the new script and it works fine

**Comment by lucasrodes** [comment]
Hi @Rouein,
I have changed the style bit. I ran the code and seems to work most of the time.

I have substituted the `driver` part to use the Context Manager (i.e. using `with`). Could you just test it once on your end?

https://github.com/owid/covid-19-data/blob/95c6f90df156a3252b00695744ba094a9bd51c2d/scripts/src/cowidev/vax/incremental/iran.py#L30-L39

and

https://github.com/owid/covid-19-data/blob/95c6f90df156a3252b00695744ba094a9bd51c2d/scripts/src/cowidev/vax/incremental/iran.py#L53-L54

Happy to roll back to `.quit`. Both work for me most time.

**Comment by Rouein** [comment]
I got `NameError: name 'date_converter' is not defined`

**Comment by Rouein** [comment]
The functions should be placed before the `if __main__`

**Comment by Rouein** [comment]
I wrote the code originally like that but again it's not dependent and if automation is ran at certain time frame it will not work , can't figure the logic at the back end
you can still use the `with` but to have reliable result , no matter when the script is ran, I recommend `quit()` and new drive instance to be there.

**Comment by lucasrodes** [comment]
If you can edit and bring back the non-`with` approach Ill be happy to merge and test on the next update (in ca.10 hours)

**Comment by Rouein** [comment]
It should be good to go (tested it on my end ). I had to check the processes to make sure a new instance was being created and the old one destroyed so i made a few changes also I put them in the loop, in case we browse more than one page. added some Typing and ran old and other urls to make sure I catch any bugs.

**Comment by lucasrodes** [comment]
I'm currently getting

```
cowid-vax get -c iran
['get']
-- Getting data... --
2022-01-16 12:13:32 INFO     VAX - cowidev.vax.incremental.iran: started
2022-01-16 12:13:40 ERROR    VAX - cowidev.vax.incremental.iran: ❌ Message: no such element: Unable to locate element: {"method":"css selector","selector":".news-content"}
  (Session info: headless chrome=87.0.4280.66)
Traceback (most recent call last):
  File "/home/.../covid-19-data/scripts/src/cowidev/vax/cmd/get_data.py", line 52, in run
    module.main(*args)
  File "/home/.../covid-19-data/scripts/src/cowidev/vax/incremental/iran.py", line 139, in main
    Iran().export()
  File "/home/.../covid-19-data/scripts/src/cowidev/vax/incremental/iran.py", line 125, in export
    data = self.read().pipe(self.pipeline)
  File "/home/.../covid-19-data/scripts/src/cowidev/vax/incremental/iran.py", line 35, in read
    data, proceed, new_driver = self._parse_data(driver)
  File "/home/.../covid-19-data/scripts/src/cowidev/vax/incremental/iran.py", line 55, in _parse_data
    text = new_driver.find_element_by_class_name("news-content").text
  File "/home/.../covid-19-data/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/home/.../covid-19-data/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/.../covid-19-data/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/.../covid-19-data/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".news-content"}
  (Session info: headless chrome=87.0.4280.66)

```

**Comment by lucasrodes** [comment]
I'll be merging for now. Thanks for your help and let's track this day how the process runs

And may roll back if we get a large amount of failed attempts.

**Comment by Rouein** [comment]
it seems to be the same issue , the website expects the cookie sent with the first connection to be decoded with js and sent back with a second connection , then perhaps there is a manual IP confirmation in the backend if the cookie is not sent back. I might be able to solve it. I run some tests locally and if successful. either I open another pull request or an issue , depending on which you prefer.

**Comment by lucasrodes** [comment]
New PR editing the already merged file should be fine! 

Thanks

**Comment by Rouein** [comment]
you are very welcome

**Pull request merged**
