### PR TITLE
enhance(test): Vanuatu automation

### PR DESCRIPTION
**Pull request by Rouein**

### CODE REVIEW

**Review by camappel — APPROVED** [review]
LGTM

**Review by lucasrodes — APPROVED** [review]
LGTM, thanks @Rouein.

@camappel wouldn't #2563 actually deprecate this? Feel free to merge if you consider this needed, otherwise, we can wait until #2563 is finalized and drop this.

**Comment by Rouein** [comment]
> LGTM, thanks @Rouein.
> 
> @camappel wouldn't #2563 actually deprecate this? Feel free to merge if you consider this needed, otherwise, we can wait until #2563 is finalized and drop th

**Review by camappel — APPROVED** [review]
Thanks @Roeuin.

Unfortunately, however, it looks like the reporting structure changed in week 10, and they no longer report the exact number of tests performed.

I will reach out to the Ministry to see if they can include this data again.

**Pull request merged**
