### PR TITLE
Update Philippines Vaccination

### PR DESCRIPTION
**Pull request by lawgimenez**

### CODE REVIEW

**Comment by edomt** [comment]
Thank you!

**Comment by lawgimenez** [comment]
No problem. Just curious why was it not merged?

**Comment by edomt** [comment]
For many countries we input the data manually in an external shared spreadsheet, so we can't merge directly (the file you're modifying in your PRs is only an output file, so it'd get overwritten automatically at the next update).

See #250 for more information.

**Comment by lawgimenez** [comment]
Okay thanks!

**Pull request closed without merging**
