### PR TITLE
VAX: Update Tunisia 2021-08-09

### PR DESCRIPTION
**Pull request by mouhib876**
Total doses administrated:3 958 514
First dose:2 553 578
Fully vaccinated:1 404 936

### CODE REVIEW

**Comment by lucasrodes** [comment]
Thanks, @mouhib876!

I Can't find these numbers in the source. Could you point me to where they appear?

**Comment by mouhib876** [comment]
You have the details of 7 of August 
Tunisia start a big campaign of vaccination on 8 august has been vaccinated 551 008 with only first dose on that day with simple equation you will get it 
The details of 7 August 
Total doses administrated: 3 293 114
First dose: 2 048 054
Fully vaccinated: 1 404 936
So 8 August it was: 3 293 114 +551 008=3 958 514 dose
First dose will bee: 2 048 054 + 551 008=2 553 578
And fully vaccinated still the same: 1 404 936

**Comment by mouhib876** [comment]
Hi I send you the vaccination update for Tunisia 17 hours ago and there's
no respond on it 🤔🤔🤔

**Comment by lucasrodes** [comment]
Hi @mouhib876,
Thanks for your contribution.

Please be patient before closing an issue. We have limited resources and we will address your issue when we have time (hopefully soon)

**Comment by mouhib876** [comment]
Ok you will have the data for 12 august for Tunisia in pull requests
Thank you for the effort and god job ❤❤

**Comment by mouhib876** [comment]
It's only my request does not have a respond 🤔🤔🤔

**Pull request closed without merging**
