### PR TITLE
VAX: Automate Serbia

### LINKED ISSUE #550: Review, consolidate and update data for Serbia
Hi @edomt ,

I have noticed that the data stopped being updated after Feb 14th for Serbia. 

In order to help resolve the issue I have collected the list of data sources for pull requests that contain the news articles since the first mention number of the fully vaccinated persons. 

If you need further help with translation/validation I will be happy to assist. Furthermore, I attempt to reach the government officials (official channels, social media, private contacts...) in order to ask them to provide automated feed, sadly no success yet. 

Please study the entries and notes I have provided bellow.

PR | Publication date | Vaccinated | 2nd | 1st | Note | Link | Original sentence | English translation
-- | -- | -- | -- | -- | -- | -- | -- | --
#448 | 07.02.2021 | 544209 | 0 | 544209 | The article mentiones that the   second dose of the mass vaccination will start from 09.02.2021 | https://www.danas.rs/drustvo/vakcinu-protiv-korona-virusa-u-srbiji-do-sada-primilo-544-209-osoba/ | Vakcinu protiv korona virusa u   Srbiji je do sada dobilo 544.209 osoba, a u utorak, 9. februara, kako je   najavljeno, počinje i revakcinacija. | So far 544209 persons have   received vaccine. On Tuesday Feb 9th, as announced, the revaccination starts.
#468 | 10.02.2021 | 592634 | 47665 | 544969 |   | https://www.alo.rs/vesti/drustvo/592-634-primilo-vakcinu-sve-veci-broj-revakcinisanih/383807/vest | Prema   najnovijim podacima, u Srbiji je do sada ukupno vakcinisano 592.634 ljudi,   dok je 47.665 osoba primilo drugu dozu vakcine. | According to the lates data, a total of 592.634 people have been  vaccinated, among them 47.665 persons have   received second dose of vaccine.
#475 | 11.02.2021 | 636119 | 83262 | 552857 |   | https://www.kurir.rs/amp/3622973/danas-tacno-2000-novozarazenih-najnoviji-korona-presek-u-srbiji-15-preminulih-raste-broj-pacijenata-na-respiratorima | Dosad je ukupno vakcinisano   636.119 građana dok je drugu dozu primilo 83.262. | Until now 636.119 citizens   have been vaccinated, among them 83.262 have received second dose.
#486 | 13.02.2021 | 803319 | NO DATA | NO DATA | I could   not locate the information on number of fully vaccinated for this data point.   IMHO: it should be omitted | https://nova.rs/vesti/drustvo/u-srbiji-vakcinisano-803-319-ljudi/ | U Srbiji   je, prema najnovijim podacima Vlade, 803.319 ljudi vakcinisano protiv   koronavirusa. | According to the latest data provided by Government, 803.319 people   habe been vaccinated against corona virus.
#497 | 16.02.2021 | 944222 | 304767 | 639455 |   | https://www.redportal.rs/srbija/12168/korona-u-srbiji-skoro-1900-novozarazenih-16-preminulo | U Srbiji je ukupno vakcinisano   944.222, dok je revakcinisano 304.767 osoba.          U Srbiji je ukupno vakcinisano 944.222 (osoba), dok je revakcinisano   304.767 osoba. | In Serbia total of 944.222   (persons) has been vaccinated, among them 304.767 persons have been   revaccinated.          Note: adjective in Serbien language has to be alligned with a noun both in   term of multiplicity, gender and case.    Due to this fact a noun can be omitted if it is later mentioned in the   same sentence with again compliant multiplicity, gender and case. In this   case "osoba" (persons) was omitted from the first part of sentence.
#497 | 17.02.2021 | 1002949 | 356010 | 646939 | For   17.02.2021, initial pull request contains incorrect data for total number of   vaccination. Most likely the article got updated in the meanwhile. | https://www.rtv.rs/sr_lat/drustvo/u-srbiji-945.989-vakcinacija-druga-u-evropi-sedma-u-svetu_1209637.html | Do sada   je vakcinisano 1.002.949 građana. | Up to now 1.002.949 citizens have been vaccinated
#523 | 18.02.2021 | 1111000 | Impossible value: 694488 | #VALUE! | This data entry is invalid and   should be removed. I tried my best to locate alternative data source. My   assumption is that the health offical either switched 2nd and 1st dose or was   misquoted by the journalist. All other articles seem to derive the text from   the original, provided by the news agency FoNet/Beta. Note: I also tried   switching the values, and it was consistant with prior and later numbers, but   this data point can not be used. | https://www.danas.rs/drustvo/krizni-stab-vakcinisano-1-111-000-gradjana-drugu-dozu-primilo-skoro-695-000/ | Pokrajinski sekretar za   zdravstvo Zoran Gojković izjavio je da je do danas protiv korona virusa u   Srbiji vakcinisano 1.111.000 ljudi i naglasio da Krizni štab ne može „da ide   i pojedično osuđuje za ponašanje koje nije u skladu sa epidemiloškim merama“. | Provincial secretary Zoran   Gojkobvić has  announced that until   today 1.111.000 people have been vaccinated and empasised that the Crisis   Headquarter can not be held responsible for penalizing the individual   diviations from the epidemic measures.
#525 | 20.02.2021 | 1136131 | 418917 | 717214 | This one   was not provided within pull request but rather as issue. I can confirm the   translated figures | https://www.rts.rs/page/stories/sr/%D0%9A%D0%BE%D1%80%D0%BE%D0%BD%D0%B0%D0%B2%D0%B8%D1%80%D1%83%D1%81/story/3134/koronavirus-u-srbiji/4265914/korona-srbija-podaci-zarazeni.html | Prema   najnovijim podacima Vlade, u Srbiji je dato 1.136.131 doza vakcina protiv   kovida. | According to the latest data provided by government, 1.136.131 dosis of   vaccines against covid have given.
#544 | 23.02.2021 | 1263111 | 451658 | 811453 |   | https://www.b92.net/info/vesti/index.php?yyyy=2021&mm=02&dd=23&nav_category=12&nav_id=1816193 | U Srbiji je, prema najnovijim   podacima Vlade, izvršeno 1.263.111 vakcinacija protiv koronavirusa, a 451.658   građana dobilo je drugu vakcinu. | In Serbia, according to the   latest data form Government, 1.263.111 vaccination against corona virus has   been executed and 451.658 citizens has received the second vaccine.
#550 | 23.02.2021 | 1.275.844 | 462578 | 813.266 |   | https://nova.rs/vesti/drustvo/nova-rs-otkriva-koliko-je-ljudi-zaista-vakcinisano-u-srbiji/ | "Prvu   dozu vakcine je primilo 813.266 građana, dok je drugu dozu primilo njih   462.578”, navode iz Kancelarije za IT i eUpravu za Nova.rs.          Dalje, preciziraju da je u Srbiji, sa današnjim presekom, ukupno bilo   1.275.844 vakcinacija, od čega revakcinacija 462.578. | "First dose of vaccine has been received by 813.266 citizens,   while the second dose of vaccine has been received by 462.578", quated   from the "Office for IT and eGovernment" for the portal   Nova.rs.          Further, they precisely say that today with current state a total of   1.275.844 of vaccinations have been made, of which 462.578 2nd.

### PR DESCRIPTION
**Pull request by lucasrodes**
Fixes #550

### CODE REVIEW

**Comment by edomt** [comment]
Great! This will save some time :)

**Comment by goranopacic** [comment]
Hi @edomt  @lucasrodes 
I'm not sure if this automation is great idea. There is a report on new numbers at https://www.rts.rs/page/stories/sr/%D0%9A%D0%BE%D1%80%D0%BE%D0%BD%D0%B0%D0%B2%D0%B8%D1%80%D1%83%D1%81/story/3134/koronavirus-u-srbiji/4344563/koronavirus-srbija-podaci-22.-april-2021..html and this site https://vakcinacija.gov.rs is not updated yet.

I think you should wait for a couple of days to see if they are actually updating it.

**Comment by goranopacic** [comment]
Hi @edomt if you reopen #550 I'll keep updating it till we see that gov is actually updating this new site.

**Comment by goranopacic** [comment]
hi @lucasrodes 
I was not the original creator of #550.
Can you reopen it?
I've added report for Apr 22 in #550

**Comment by goranopacic** [comment]
hi @lucasrodes 
gov site has been updated at about 7pm yesterday with the latest numbers (newer/higher than mine delivered at 3pm).
that looks promising.

**Pull request merged**
