### PR TITLE
VAX: New vaccines in Ukraine

### PR DESCRIPTION
**Pull request by isorochan**
Ukraine started using Sinovac from 14.04 and  Pfizer/BioNTech from 18.04

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @isorochan,
Could you provide a source for this? 

Thanks

**Comment by isorochan** [comment]
We have a special dashboard from the National Security and Defense Council of Ukraine.
https://health-security.rnbo.gov.ua/vaccination

This Dashboard aggregates and visualizes data from the National Health ministry

image

**Comment by lucasrodes** [comment]
Thanks, @isorochan! This is a really nice dashboard.

From what I see, I think we could modify our [`automation script`](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/src/vax/incremental/ukraine.py) to import the data directly from the underlying API in your dashboard instead of relying on scraping the HTML at https://vaccination.covid19.gov.ua/. This perhaps would include also historical data.

**Comment by isorochan** [comment]
@lucasrodes 
I will check maybe I can find source data that is used  in this dashboard

**Review by edomt — APPROVED** [review]

**Pull request merged**
