### PR TITLE
Various updates and new entries

### PR DESCRIPTION
**Pull request by unguaio**
Please check this updates and let me know!

### CODE REVIEW

**Comment by unguaio** [comment]
Hello! I'd like to report some different updates, if it's not a problem!
First of all, I noticed that there was an error about Monaco's last day of updates, which is 7 May and that there was also an error about Myanmar's overall vaccinated, which is 1.9 million and not 1.8 million (https://www.rfa.org/english/news/myanmar/third-wave-05042021205514.html)!
Moreover, many countries has got more recent updates via WHO site, like:


BELARUS https://covid19.who.int/region/euro/country/by

HONDURAS https://covid19.who.int/region/amro/country/hn

NICARAGUA https://covid19.who.int/region/amro/country/ni

JAMAICA https://covid19.who.int/region/amro/country/jm

TAJIKISTANhttps://covid19.who.int/region/euro/country/tj

TURKMENISTANhttps://covid19.who.int/region/euro/country/tm

YEMENhttps://covid19.who.int/region/emro/country/ye

MAURITANIA https://covid19.who.int/region/afro/country/mr

MALI https://covid19.who.int/region/afro/country/ml

SUDAN https://covid19.who.int/region/emro/country/sd

DJIBOUTI https://covid19.who.int/region/emro/country/dj

SOMALIA https://covid19.who.int/region/emro/country/so

GUINEA BISSAUhttps://covid19.who.int/region/afro/country/gw

LIBERIAhttps://covid19.who.int/region/afro/country/lr

TOGO https://covid19.who.int/region/afro/country/tg

BENINhttps://covid19.who.int/region/afro/country/bj

SAO TOME & PRINCIPE https://covid19.who.int/region/afro/country/st

CAMEROON https://covid19.who.int/region/afro/country/cm

CONGO https://covid19.who.int/region/afro/country/cg

DEMOCRATIC REPUBLIC OF CONGO https://covid19.who.int/region/afro/country/cd

SOUTH SUDAN https://covid19.who.int/region/afro/country/ss

RWANDA https://covid19.who.int/region/afro/country/rw

COMOROS https://covid19.who.int/region/afro/country/km

MAURITIUS https://covid19.who.int/region/afro/country/mu

MOZAMBIQUE https://covid19.who.int/region/afro/country/mz

LESOTHO https://covid19.who.int/region/afro/country/ls

MADAGASCAR https://covid19.who.int/region/afro/country/mg


In the end, Ethiopia and Kosovo has updated their counts, but I cannot understand their numbers:

https://twitter.com/FMoHealth/status/1392905764352765955/photo/1

https://www.facebook.com/Ministria.Shendetesise.RKS/


Thank you for your attention, hope it helped your great work and sorry for the long mail!

Regards,

Matteo

________________________________
Da: Edouard Mathieu ***@***.***>
Inviato: martedì 11 maggio 2021 14:31
A: owid/covid-19-data ***@***.***>
Cc: unguaio ***@***.***>; Author ***@***.***>
Oggetto: Re: [owid/covid-19-data] Various updates and new entries (#1322)


@edomt commented on this pull request.

Thank you - we'll update our data accordingly.

**Comment by edomt** [comment]
Thank you!

**Comment by unguaio** [comment]
Hello, sorry for the message, just a simple question! Why some countries which uses who data, like Bahamas, Jamaica, Rwanda, Mali and Mauritania, are not among the ones with automated updates according to this link
https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/src/vax/incremental/who.py ? Thank you for your attention and for your great work!

________________________________
Da: Edouard Mathieu ***@***.***>
Inviato: martedì 11 maggio 2021 14:31
A: owid/covid-19-data ***@***.***>
Cc: unguaio ***@***.***>; Author ***@***.***>
Oggetto: Re: [owid/covid-19-data] Various updates and new entries (#1322)


@edomt commented on this pull request.

Thank you - we'll update our data accordingly.

**Comment by edomt** [comment]
Hi @unguaio 

It depends on whether we're able to collect public data ourselves.

- Bahamas: updates are regularly published on Facebook (e.g. [here](https://www.facebook.com/opmbs/posts/817591312296181))
- Mali: updates are regularly published on Facebook (e.g. [here](https://www.facebook.com/msdsmali1/posts/2977834499112715))
- Mauritania: updates are regularly published in PDF reports (e.g. [here](https://www.sante.gov.mr/wp-content/uploads/2021/05/Mauritania-COVID-19-Situation-Report-2021-05-23FR.pdf))
- Jamaica: we've now switched to WHO as our source
- Rwanda: we've now switched to WHO as our source

But if some of the countries that publish regularly themselves ever stop doing so, we'll then switch over to the WHO data for them as well.

**Comment by unguaio** [comment]
Hello, thank you for your work,
I'd like to submit these random facts:

  *   First of all Kiribati has just started vaccinations: https://www.rnz.co.nz/international/pacific-news/443374/kiribati-to-start-covid-19-vaccination-rollout
  *   About automated updates, these countries could be added to the WHO list: Bahamas, Grenada, Mali and Mauritania.
  *   Moreover, the official pages of the following countries, in which we found latest updates, could be added to the automation system, if it works with data "hold" in pictures and not in a page (dont know if the system can locate and elaborate data this way): AntiguaBarbuda, Bhutan, Dominica, Ethiopia, Gabon, Laos, St KittsNevis, St Vincent Gr. and probably even some others too!
  *   In the end, the unique case of Vatican City, the only independent Country which has already with every probability vaccinated all its citizens: in fact in this site from 5th of February, https://www.famigliacristiana.it/articolo/cosi-la-citta-del-vaticano-sta-gestendo-le-vaccinazioni.aspx, its reported that at least 5.000 vaccines has been administered yet.
  *   Thank you for your attention, hope it helped,
  *   Matteo

**Comment by lucasrodes** [comment]
Hi @unguaio, thanks for reporting. On your points:

- Well keep an eye on Kiribati's campaign to see if they release any figures.
- We have added Mauritania to WHO script.
- We only implement automation for sources that have the figures in plain text. We tried image detection in the past but it is prone to errors.

Thanks

**Pull request closed without merging**
