### PR TITLE
Update Panama.csv

### PR DESCRIPTION
**Pull request by mmorenoc25**
Vaccination update against COVID-19 in the Republic of Panama corresponding to April 15, 2021 reported by the Ministry of Health.

### CODE REVIEW

**Comment by lucasrodes** [comment]
Hi @mmorenoc25,
Thanks for your contribution!

Could you help me find the numbers that you report in the [source link](https://twitter.com/MINSAPma/status/1382832727108546565/photo/2)? 

I can only find the number of total_vaccinations
> [...] se han aplicado 550,860 dosis en todo el país

Thanks once again

**Comment by mmorenoc25** [comment]
Hello Mr. 
The numbers of total_vaccinations are published in the Daily report of the Ministry of Health of Panama on Twitter, Instagram and the official website of the Ministry, however, the number of the second dose is on the official page https://vacunas.panamasolidario.gob.pa/vacunometro/ Which are published as the vaccines are applied. However, there is no real number of vaccines applied with a difference of approximately 25,000 in the statement and the website. The second dose data are those available on that official website of the government of Panama.

**Comment by lucasrodes** [comment]
I am not able to connect to https://vacunas.panamasolidario.gob.pa/vacunometro/. Apparently an ArcGIS account is required. Could you confirm this?

Thanks @mmorenoc25

**Comment by mmorenoc25** [comment]
Good Morning 

Right now they are updating the page. Tomorrow a new circuit starts and today they update it for tomorrow.

**Comment by lucasrodes** [comment]
Thanks, @mmorenoc25,
I have added new references and data points to our dataset. Public data will be updated in the next update.

**Pull request closed without merging**
