### PR TITLE
US : Vaccination by age group

### PR DESCRIPTION
**Pull request by covid19owid**
Hi @lucasrodes

Vaccination by age group for US has been updated. Can you please provide your reviews and comments.

Thank you.

### CODE REVIEW

**Comment by lucasrodes** [comment]
Thanks, @covid19owid!

Note that `total_vaccinations` **cannot be estimated by the sum of first doses and second doses** as the US uses single-shot vaccines.**

Therefore, with this source, we cannot obtain `total_vaccinations` but perhaps `people_vaccinated`. I have changed the output so it provides `people_vaccinated`. However, if we add up the values of `people_vaccinated` it does not match the one in [United States.csv](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/output/United%20States.csv). Take 2021-06-06 as an example. In the age file, we obtain after adding up all groups 157738203, but in the main file, we have that 170833221 people have been vaccinated so far. Could you check where this miss-alignment is coming from? I suspect it may be something related to J&J. In that case, we may not be able to even estimate people_vaccinated.

On another note, I have added some changes; please make sure you understand them before creating new PRs. Let me know if you have any questions. I basically refactored the code, trying to reduce redundancy and comply with the structure. Most of my changes have been explained in https://github.com/owid/covid-19-data/pull/1494#issuecomment-855961961

**Comment by lucasrodes** [comment]
Hi @covid19owid,
[Requirements](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/CONTRIBUTE.md#age-group-data) have changed. We believe this data is more relevant to our audience.

I am not sure if this is available in the source data.

**Comment by covid19owid** [comment]
Hi @lucasrodes,

Thanks a lot for the reviews and suggestions. Will follow them for the subsequent PRs. It looks like the vaccination data by age may not be complete 100% from the source ( https://www.cdc.gov/coronavirus/2019-ncov/vaccines/distributing/demographics-vaccination-data.html ) the data is pulled from. It has missing data which is not published. That's the reason we are seeing a difference for people_vaccinated on 2021-06-06.

Lucas, please let me know if we have to even consider this data given that it may not be 100% accurate.

Thank you!

**Comment by covid19owid** [comment]
Hi @lucasrodes,  

The data published on the site ( https://www.cdc.gov/coronavirus/2019-ncov/vaccines/distributing/demographics-vaccination-data.html) may have missing data. Even the people_vaccinated numbers will not match the source (https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/output/United%20States.csv).

Can you please let me know your thoughts on this.

Thank you

**Comment by lucasrodes** [comment]
Merging because it has substantial code style improvements. Merging without age steps and age data (because not aligned with main data)

**Pull request merged**
