### PR TITLE
refactor(vax, Mexico): Changing dependencies

### PR DESCRIPTION
**Pull request by Rouein**
now using `pdftotext`

### CODE REVIEW

**Comment by lucasrodes** [comment]
The script is not working on my end:

```
~ cowid-vax get -c mexico
['get']
-- Getting data... --
2022-01-31 20:35:07 INFO     VAX - cowidev.vax.incremental.mexico: started
2022-01-31 20:35:09 ERROR    VAX - cowidev.vax.incremental.mexico: ❌ 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/path/covid-19-data/scripts/src/cowidev/vax/cmd/get_data.py", line 52, in run
    module.main(*args)
  File "/path/covid-19-data/scripts/src/cowidev/vax/incremental/mexico.py", line 106, in main
    Mexico().export()
  File "/path/covid-19-data/scripts/src/cowidev/vax/incremental/mexico.py", line 93, in export
    data = self.read().pipe(self.pipeline)
  File "/path/covid-19-data/scripts/src/cowidev/vax/incremental/mexico.py", line 21, in read
    return self._parse_data(link)
  File "/path/covid-19-data/scripts/src/cowidev/vax/incremental/mexico.py", line 52, in _parse_data
    people_vaccinated = clean_count(matches.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

Similar issue highlighted in https://github.com/owid/covid-19-data/pull/2383#pullrequestreview-868328778

**Comment by Rouein** [comment]
Interesting, I just retested it and it worked fine on my end.

**Comment by lucasrodes** [comment]
Are you using `cowid-vax` tool?

**Comment by Rouein** [comment]
are you running pdftotext - 2.2.2

**Comment by lucasrodes** [comment]
Please read https://github.com/owid/covid-19-data/pull/2383#issuecomment-1026140721.

Yes I am using pdftotext 2.2.2

**Comment by Rouein** [comment]
I tried setting up `cowid-vax` and can't get past:
```
line 103, in _get_project_dir_from_config
raise KeyError("Missing global.project_dir variable in config.yaml")
KeyError: 'Missing global.project_dir variable in config.yaml
```


However with exporting `OWID_COVID_PROJECT_DIR` and simply running `python mexico.py` (same script as per commit here) the data of `2022-01-30` which I manually deleted gets reproduced.

**Comment by Rouein** [comment]
OK, Finally:
```
cowid-vax get -c mexico
['get']
-- Getting data... --
2022-02-01 00:56:22 INFO     VAX - cowidev.vax.incremental.mexico: started
2022-02-01 00:56:25 INFO     VAX - cowidev.vax.incremental.mexico: SUCCESS ✅
2022-02-01 00:56:25 INFO     
---

RETRIES (0)
---
TIMING DETAILS
Took 2.94 seconds (i.e. 0.05 minutes).
Top 20 most time consuming scripts:
                                execution_time (sec)
module                                              
cowidev.vax.incremental.mexico                  2.93

Took 2.95 seconds (i.e. 0.05 minutes) [AFTER RETRIALS].
---
----------------------------
----------------------------
----------------------------
```

Still fine.

**Comment by lucasrodes** [comment]
This is strange. Could you check the value of `text` in line X, please?

You can add this to line 51:

```
with open("/tmp/mexico-log.txt", "w") as f:
    f.write(text)
```

to export the value of the variable to a text file.

**Value I get:**

```
COVID-19 Comunicado Técnico Diario 30 enero, 2022 17h00 Componente técnico COVID-19 Informe epidémico diario 30 enero, 2022 COVID-19 México: casos incidentes y activos estimados y personas recuperadas por semana epidemiológica Escenario nacional Fase 3 267929 350000 300000 (5.7%) 250000 Casos estimados 30 enero, 2022 casos activos estimados 200000 150000 100000 -31 % 2021 2020 2 52 50 46 48 42 44 40 36 38 32 34 30 26 28 22 24 20 16 18 12 14 10 6 8 2 4 51 53 49 45 47 41 43 39 35 37 31 33 29 25 27 21 23 17 19 13 15 9 11 5 7 1 0 3 50000 2022 Semana epidemiológica 5188828 Casos estimados 4024981 Personas recuperadas 305893 Defunciones confirmadas Fuente: SSA(SPPS/DGE/InDRE/Informe técnico.COVID-19 /México- 30 enero 2022 (corte 9:00hrs). La población total de México se asume en 126014024 y la población mayor de edad 83452050 (quinquenios de 20 años en adelante, INEGI censo 2020) 0 01/05/2… 12/05/2… 23/05/2… 03/06/2… 14/06/2… 25/06/2… 06/07/2… 17/07/2… 28/07/2… 08/08/… 19/08/2… 30/08/2… 10/09/2… 21/09/2… 02/10/2… 13/10/2… 24/10/2… 04/11/2… 15/11/20… 26/11/20… 07/12/2… 18/12/2… 29/12/2… 09/01/2… 20/01/2… 31/01/2… 11/02/2… 22/02/2… 05/03/2… 16/03/2… 27/03/2… 07/04/… 18/04/2… 29/04/2… 10/05/2… 21/05/2… 01/06/2… 12/06/2… 23/06/2… 04/07/… 15/07/2… 26/07/2… 06/08/… 17/08/2… 28/08/2… 08/09/… 19/09/2… 30/09/2… 11/10/20… 22/10/2… 02/11/2… 13/11/20… 24/11/2… 05/12/2… 16/12/20… 27/12/2… 07/01/2… 18/01/2… 29/01/2… Personas hospitalizadas COVID-19 México: situación de hospitalización, camas generales y camas con ventilador mecánico Escenario nacional 30000 25000 20000 15000 10000 5000 Total de personas hospitalizadas Ocupación - camas generales Sin cambio 45% FUENTE: RED IRAG, acumulado del 30 enero 2022. - SSA/SPPS/DGTI/SERVICIOS DE SALUD ESTATALES Ocupación - camas con ventilador Sin cambio 29% 30 enero, 2022 Fase 3 -65% reducción de ocupación nacional (máximo vs. hoy) COVID-19 México: mortalidad por semana epidemiológica de defunción 30 enero, 2022 Escenario nacional Fase 3 8 7 5 4 3 2 2021 2020 Semana epidemiológica de defunción FUENTE: RED IRAG, acumulado del 30 enero 2022. - SSA/SPPS/DGTI/SERVICIOS DE SALUD ESTATALES 2 52 50 46 48 42 44 40 36 38 32 34 30 26 28 22 24 20 16 18 12 14 10 6 8 2 4 51 53 49 45 47 41 43 39 35 37 31 33 29 25 27 21 23 19 15 17 13 9 11 5 7 0 1 1 3 mortalidad por cada 100mil habitantes 6 2022 Estrategia Nacional de Vacunación Panorama General, COVID-19 30 enero, 2022 Estrategia Nacional de Vacunación Avance diario (dosis)* 1800000 COVID-19 373673 1600000 1400000 Dosis aplicadas reportadas 1200000 Dosis aplicadas 30 enero, 2022 1000000 800000 600000 400000 200000 0 Fecha de vacunación *Datos preliminares, corte de información al 30 enero 2022, datos estimados por histórico reportado Estrategia Nacional de Vacunación 30 enero, 2022 Avance acumulado (dosis)* COVID-19 180000000 165543906 160000000 140000000 Total de dosis aplicadas reportadas Dosis aplicadas 120000000 100000000 80000000 60000000 40000000 20000000 Fecha *Datos preliminares, corte de información al 30 enero 2022, datos estimados por histórico reportado 100009 dosis perdidas Estrategia Nacional de Vacunación Personas vacunadas* Esquema completo Nuevos esquemas 77129336 6483222 Personas vacunadas con esq. completo Personas vacunadas con nuevos esquemas 93% *Datos preliminares, corte de información al 30 enero 2022, datos estimados por histórico reportado. Todas las edades. 7% 30 enero, 2022 COVID-19 83612558 Personas vacunadas reportadas Aguascalientes Baja California Baja California Sur Campeche Chiapas Chihuahua Ciudad de México Coahuila Colima Durango Estado de México Guanajuato Guerrero Hidalgo Jalisco Michoacán Morelos Nayarit Nuevo León Oaxaca Puebla Querétaro Quintana Roo San Luis Potosí Sinaloa Sonora Tabasco Tamaulipas Tlaxcala Veracruz Yucatán Zacatecas 10% 0% 93% 92% 92% 89% 70% 89% 100% 88% 84% 89% 95% 90% 75% 93% 83% 85% 85% 82% 93% 76% 89% 99% 99% 95% 93% 85% 92% 90% 92% 80% 91% 92% Porcentaje Estrategia Nacional de Vacunación Cobertura por entidad* 90% 80% 70% 60% 30 enero, 2022 COVID-19 100% 89% De la población de 18 años y más 50% 40% 30% 20% *Población con al menos 1 dosis; estimación conforme a entrega y aplicación de dosis. Corte al 30 enero 2022. Se toma como población de 18 años o más, un total 89484507 personas (proyección de población a mitad de año 2022, CONAPO). Estrategia Nacional de Vacunación 30 enero, 2022 Vacunas recibidas (dosis)* 51433395 20000000 88119500 14124840 20000000 201299735 *Dosis recibidas en México y con corte de información al 30 enero 2022. COVID-19 6272000 1350000 Total de dosis recibidas desde el 23 de diciembre de 2020 
```

**Comment by Rouein** [comment]
I got:
```
COVID-19 Comunicado Técnico Diario 17h00 30 enero, 2022 Componente técnico COVID-19 Informe epidémico diario 30 enero, 2022 COVID-19 México: casos incidentes y activos estimados y personas recuperadas por semana epidemiológica 30 enero, 2022 Escenario nacional Fase 3 267929 350000 300000 (5.7%) 250000 casos activos estimados Casos estimados 200000 150000 100000 50000 -31 % 0 1 3 5 7 9 11 13 17 21 23 25 27 29 31 33 35 37 39 41 43 51 53 6 8 18 26 30 36 38 15 19 45 47 49 20 22 24 28 32 34 48 50 52 2 4 10 12 14 16 40 42 44 46 2 2020 2021 2022 Semana epidemiológica 5188828 Casos estimados 4024981 Personas recuperadas 305893 Defunciones confirmadas Fuente: SSA(SPPS/DGE/InDRE/Informe técnico.COVID-19 /México- 30 enero 2022 (corte 9:00hrs). La población total de México se asume en 126014024 y la población mayor de edad 83452050 (quinquenios de 20 años en adelante, INEGI censo 2020) Personas hospitalizadas 0 5000 10000 15000 20000 25000 30000 01/05/2… 12/05/2… 23/05/2… Total de personas 03/06/2… 14/06/2… 25/06/2… 06/07/2… 17/07/2… hospitalizadas 28/07/2… 08/08/… 19/08/2… 30/08/2… 10/09/2… 21/09/2… 02/10/2… 13/10/2… 24/10/2… Escenario nacional 04/11/2… Sin 15/11/20… 26/11/20… cambio 07/12/2… 18/12/2… 29/12/2… 09/01/2… 20/01/2… FUENTE: RED IRAG, acumulado del 30 enero 2022. - SSA/SPPS/DGTI/SERVICIOS DE SALUD ESTATALES 31/01/2… 11/02/2… 22/02/2… 05/03/2… 16/03/2… COVID-19 México: situación de hospitalización, camas 27/03/2… 07/04/… 18/04/2… Ocupación - camas generales 29/04/2… 45% 10/05/2… 21/05/2… 01/06/2… 12/06/2… 23/06/2… 04/07/… 15/07/2… Sin 26/07/2… 06/08/… 17/08/2… cambio 28/08/2… 08/09/… 19/09/2… 30/09/2… 11/10/20… 22/10/2… 02/11/2… 13/11/20… 24/11/2… 05/12/2… 16/12/20… 27/12/2… 07/01/2… Ocupación - camas con ventilador 18/01/2… 29% 29/01/2… generales y camas con ventilador mecánico reducción de ocupación Fase 3 30 enero, 2022 nacional (máximo vs. hoy) -65% COVID-19 México: mortalidad por semana epidemiológica de defunción 30 enero, 2022 Escenario nacional Fase 3 8 7 6 mortalidad por cada 100mil habitantes 5 4 3 2 1 0 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 2 2020 2021 2022 Semana epidemiológica de defunción FUENTE: RED IRAG, acumulado del 30 enero 2022. - SSA/SPPS/DGTI/SERVICIOS DE SALUD ESTATALES Estrategia Nacional de Vacunación Panorama General, COVID-19 30 enero, 2022 Estrategia Nacional de Vacunación 30 enero, 2022 Avance diario (dosis)* COVID-19 1800000 1600000 1400000 373673 Dosis aplicadas reportadas 1200000 Dosis aplicadas 1000000 800000 600000 400000 200000 0 Fecha de vacunación *Datos preliminares, corte de información al 30 enero 2022, datos estimados por histórico reportado Estrategia Nacional de Vacunación 30 enero, 2022 Avance acumulado (dosis)* COVID-19 180000000 165543906 160000000 140000000 Total de dosis aplicadas reportadas 120000000 Dosis aplicadas 100000000 80000000 60000000 40000000 20000000 - Fecha 100009 dosis perdidas *Datos preliminares, corte de información al 30 enero 2022, datos estimados por histórico reportado Estrategia Nacional de Vacunación 30 enero, 2022 Personas vacunadas* COVID-19 Esquema Nuevos 83612558 completo esquemas Personas vacunadas reportadas 77129336 6483222 Personas vacunadas Personas vacunadas con esq. completo con nuevos esquemas 93% 7% *Datos preliminares, corte de información al 30 enero 2022, datos estimados por histórico reportado. Todas las edades. Porcentaje 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% Aguascalientes 93% Baja California 92% Baja California Sur 92% Campeche 89% Chiapas 70% Chihuahua 89% Ciudad de México 100% Coahuila 88% Colima 84% Durango 89% Estado de México 95% Guanajuato 90% Guerrero 75% Hidalgo 93% Jalisco 83% Michoacán 85% Morelos 85% Nayarit 82% Nuevo León 93% Oaxaca 76% Puebla 89% Querétaro 99% Quintana Roo 99% San Luis Potosí 95% Cobertura por entidad* Sinaloa 93% Sonora 85% Estrategia Nacional de Vacunación Tabasco 92% Tamaulipas 90% Tlaxcala 92% Veracruz 80% Yucatán 91% Zacatecas 92% De la población *Población con al menos 1 dosis; estimación conforme a entrega y aplicación de dosis. Corte al 30 enero 2022. Se toma como población de 18 años o más, un total 89484507 personas (proyección de población a mitad de año 2022, CONAPO). COVID-19 de 18 años y más 89% 30 enero, 2022 Estrategia Nacional de Vacunación 30 enero, 2022 Vacunas recibidas (dosis)* COVID-19 51433395 20000000 14124840 6272000 88119500 20000000 1350000 201299735 Total de dosis recibidas desde el 23 de diciembre de 2020 *Dosis recibidas en México y con corte de información al 30 enero 2022.
```

**Comment by Rouein** [comment]
what is your poppler-cpp-devel version?

**Comment by lucasrodes** [comment]
How can I find the version? I am struggling to find out

**Comment by Rouein** [comment]
that's it I have 0.4.9

**Comment by Rouein** [comment]
I am on an Ubuntu based system so can't really tell how libpoppler version compares but given that my poppler-data is older I assume I have the older version of libpoppler too.

**Comment by lucasrodes** [comment]
Perhaps that's it, but unsure. I know me and @camappel were getting it to work on different machines (Arch and Mac). I assume both with the latest versions.

---
As a side comment, I found [pdfminer.six](https://github.com/pdfminer/pdfminer.six/issues), which seems to be a more actively maintained library

**Comment by Rouein** [comment]
Given that it is an open source repo, it is better to move to a different library that is pure python. That way, you don't need to set up reliability checks and docker tests for a uniform experience across all platforms.  

I don't know which timeline you are in but its 3am over here, so tomorrow, I will give this library a try and if its stable I can refactor all the pdf scripts to use it.(although this week I might have a heavy workload, so it wouldn't be as fast) and when I get time I can set up a docker to test the script from now on before it is pushed.(you can set it up with github acctions)
P.S. if we set up a slack channel for communications rather than spamming the pr, it would be better.

**Review by Sunidaponchai — APPROVED** [review]

**Comment by Rouein** [comment]
I implemented `pdfminer` , test it and let me know if it works.

**Comment by lucasrodes** [comment]
Thanks, @Rouein!
Works for me! Looks like `pdfminer.six` might be the way forward for, hopefully, all PDF-based data sources.

>  P.S. if we set up a slack channel for communications rather than spamming the pr, it would be better.

For the time being, we prefer to gather most of our conversations here on GitHub issues. We might re-evaluate in the future, will let you know if that is the case.

---

@edomt you will need to re-install the library to have this new dependency.

**Pull request merged**
