### PR TITLE
Algeria data(vax): update 

### PR DESCRIPTION
**Pull request by rouabas**
Update according to Algerian Prime Ministre's official statement announced on elkhabar.com

### CODE REVIEW

**Comment by rouabas** [comment]
Source 1: Official Algerian Prime Minister Facebook page (Declaration video in Arabic) https://www.facebook.com/pm.gov.dz/videos/215168490530234/
Source 2: Algerian Prime Minister announcment on elkhabar.com (https://www.elkhabar.com/press/article/190912/%D9%87%D8%B0%D8%A7-%D9%87%D9%88-%D8%B9%D8%AF%D8%AF-%D8%A7%D9%84%D9%85%D9%84%D9%82%D8%AD%D9%8A%D9%86-%D8%A7%D9%84%D9%89-%D8%BA%D8%A7%D9%8A%D8%A9-%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D8%A8%D8%A7%D9%84%D8%AC%D8%B2%D8%A7%D8%A6%D8%B1/)

**Comment by lucasrodes** [comment]
Hi @rouabas,
Thanks for your contribution.

Could you elaborate on the vaccine usage? We had been reporting Sputnik V up to date.

**Comment by rouabas** [comment]
Hi @lucasrodes 
You're most welcome!

I forgot to add Sputnik V again (now fixed), please find below the detailed doses according the the declaration of the Algerian Prime Minister:
During the month of July 2021, **9.273.200** vaccine doses has been acquired. 
As for the month of August they will have:
- **8.200.000** Sinocav vaccine doses;
- **758.000** AstraZeneca vaccine doses through Covax;
- **650.000** Sputnik V vaccine doses.
Source 1: Algeria Presse Service - https://www.aps.dz/ar/sante-science-technologie/110590-19-3-5
Source 2: Elkhabar - https://www.elkhabar.com/press/article/190912/%D9%87%D8%B0%D8%A7-%D9%87%D9%88-%D8%B9%D8%AF%D8%AF-%D8%A7%D9%84%D9%85%D9%84%D9%82%D8%AD%D9%8A%D9%86-%D8%A7%D9%84%D9%89-%D8%BA%D8%A7%D9%8A%D8%A9-%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D8%A8%D8%A7%D9%84%D8%AC%D8%B2%D8%A7%D8%A6%D8%B1/

As for the Sinopharm vaccine, **200.000** doses were previously used.
Source 1: Algeria Presse Service on Twitter (https://twitter.com/APS_Algerie/status/1364848595204194305)
Source 2: Algerian Ministry if Defense on FB (https://www.facebook.com/mdn.gov.dz/posts/281539266690928)

**Comment by lucasrodes** [comment]
Awesome, thank you very much for your contribution, @rouabas!
We will update data for Algeria in the next data update.

Note that we currently can't accept PRs for countries with manually imported data points due to how our pipeline is set up. You can find more info in our [Contribute guide](https://github.com/owid/covid-19-data/blob/master/scripts/scripts/vaccinations/CONTRIBUTE.md).

Kind regards,

**Pull request closed without merging**
