### PR TITLE
refactor(test, costa rica): python migration

### PR DESCRIPTION
**Pull request by lucasrodes**
Migrate R code to Python code

### CODE REVIEW

**Comment by Rouein** [comment]
Hi @lucasrodes ,
Can you open an issue with a list of all R scripts left. That way the community can mention which scripts they will work on so there are no conflicts. It will be a faster way of converting all the scripts.

**Comment by lucasrodes** [comment]
See #2099

**Comment by lucasrodes** [comment]
I added some changes to drop an outlier in `nue_descar` column

**Review by camappel — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
