### PR TITLE
Updating vaccinations data for Costa Rica

### PR DESCRIPTION
**Pull request by fede2cr**

### CODE REVIEW

**Comment by edomt** [comment]
Thank you

**Comment by fede2cr** [comment]
You closed this PR, didn't merge it, and then you submitted the exact same patch. What's up with that?

**Comment by fede2cr** [comment]
Actually no. You forgot to remove the fbclid fom the URL. So what is up with that as well?

**Comment by edomt** [comment]
Hi @fede2cr 

If you look closely you'll see that it's not the same commit. You added the data point to the file in the `country_data` folder, which is part of our pipeline's _output_, so it would have been overwritten right at the next update. Our input system is more complicated that this I'm afraid, and that's why we can't take direct pull requests. It's all explained in #230.

Thanks for letting me know about the fbclid though, I'll remove that. 👌

**Pull request closed without merging**
