### PR TITLE
enhance(vax,fiji): add boosters and correct vaccine timeline

### PR DESCRIPTION
**Pull request by Rouein**
#2430

### CODE REVIEW

**Comment by Rouein** [comment]
`spc.py` should be modified to not overwrite the boosters data as well as outputting the correct vaccine timeline.

**Comment by lucasrodes** [comment]
Hi @Rouein,
Thanks for reporting this.

I am trying to reconcile SPC data with official Fiji data. As per SPC, `first doses + second doses = total doses`, which might indicate that they are not considering boosters and therefore our metric `total_vaccinations` might not be accurate at the moment.

I reached out to SPC, letting them know about this case and asked if they plan to have booster data anytime soon.

---
On another note, we may need to think about how to use two scripts (batch `spc.py` and incremental `fiji.py`) to generate the data for Fiji. An option could be to:
- Have a  `main` function in `fiji.py` that doesn't do anything.
- Call methods from `cowidev.vax.incremental.fiji` in `cowidev.vax.batch.spc`, then join SPC data with Fiji data.

**Comment by lucasrodes** [comment]
Hi @Rouein,
Thanks for reporting this.

I am trying to reconcile SPC data with official Fiji data. As per SPC, `first doses + second doses = total doses`, which might indicate that they are not considering boosters and therefore our metric `total_vaccinations` might not be accurate at the moment.

I reached out to SPC, letting them know about this case and asked if they plan to have booster data anytime soon.

---
On another note, we may need to think about how to use two scripts (batch `spc.py` and incremental `fiji.py`) to generate the data for Fiji. An option could be to:
- Have a  `main` function in `fiji.py` that doesn't do anything.
- Call methods from `cowidev.vax.incremental.fiji` in `cowidev.vax.batch.spc`, then join SPC data with Fiji data.

**Comment by Rouein** [comment]
The issue is that the dates might not align. Maybe use merge data and drop duplicates by date in spc?

**Comment by Rouein** [comment]
This is my take on it(at least until they fix the total_vaccinations).

**Review by lucasrodes — APPROVED** [review]
LGTM, thanks @Rouein! Let's see if I get a reply by SPC anytime soon.

**Pull request merged**
