### PR TITLE
enhance(test, Nepal): New Country automation

### PR DESCRIPTION
**Pull request by Rouein**
[Historical data](https://github.com/owid/covid-19-data/blob/e218d1a6deb9173b12ce7df01ec88a8ef59604be/public/data/testing/covid-testing-all-observations.csv) only counts the PCR tests and according to the official reports available [here](https://covid19.mohp.gov.np/situation-report), a positive antigen test is counted as a positive case as well. The same link can be used to manually correct the data.

### CODE REVIEW

**Comment by Rouein** [comment]
Perhaps data correction could be added to #2465.

**Comment by lucasrodes** [comment]
Thanks, @Rouein.

@camappel, from what I have read we did not count antigen tests because Nepal did not consider positive antigen tests as cases? If we decided to merge this PR, we need to disable manual data collection and ad historical data to the CSV.

**Comment by Rouein** [comment]
Then I leave it to you to comment out the necessary parts in the code until backfill is complete.

**Comment by camappel** [comment]
That would be great, thanks!

**Review by camappel — APPROVED** [review]
Excellent, thanks @Rouein !

**Review by lucasrodes — APPROVED** [review]
LGTM. Appreciate your help, @Rouein

**Pull request merged**
